### ISSUE TITLE
Don't print progress in non-interactive terminal (GitHub Actions)

### ISSUE THREAD

**Issue by belluzj** [simoncozens/youseedee#6]
The hand-written progress bar at https://github.com/simoncozens/youseedee/blob/master/lib/youseedee/__init__.py#L50 will flood the logs of GitHub actions, see screenshot below: (about 2000 lines of progress)

![image](https://github.com/simoncozens/youseedee/assets/3616772/23ff8171-ab46-4dee-b93f-77e47a1328d9)

Possible idea (I didn't try on this project but have used it in the past), use tdqm: https://github.com/tqdm/tqdm

**Comment by simoncozens** [comment]
Oh good point. This was before I knew tqdm.

**Comment by belluzj** [comment]
Thanks!
